= Doorlock Firmware

This is the firmware for my doorlock. It consists of a bootloader to allow firmware updates, and the
main application.

== Prerequisites

=== Hardware

* Adafruit Feather nRF52840
* Stepper motor (for lock)
* Motor controller (DRV-8833 for instance)

=== Software

Make sure you have the latest versions (`cargo install <tool>`) of these tools:

* `probe-run`
* `probe-rs-cli`
* `cargo-flash`
* `cargo-binutils`

=== Running

Download the softdevice version 7.3.0 link:https://www.nordicsemi.com/Products/Development-software/s140/download[here].

Erase, flash bootloader, softdevice and application:

```
probe-rs-cli erase --chip nRF52840_xxAA
cargo flash --manifest-path bootloader/Cargo.toml --release --chip nRF52840_xxAA
probe-rs-cli download s140_nrf52_7.3.0_softdevice.hex --format Hex --chip nRF52840_xxAA
cargo flash --manifest-path application/Cargo.toml --release --chip nRF52840_xxAA
```

=== Updating using firmware updates

One change you can do is to set the REVISION environment variable We can then rebuild the application and flash it using the `drgdfu` tool.

```
REVISION=myupdate cargo objcopy --manifest-path application/Cargo.toml --release -- -O binary update.bin
drgdfu generate --version myupdate --file update.bin > update.json
drgdfu upload ble-gatt --device F8:56:35:45:1C:3C file update.json
```

Be patient! The firmware update process on the device takes up to 20-30 seconds.

Once finished, the `drgdfu` tool will wait for the device to swap the new firmware and report back the expected version. If not, it will restart the DFU process.
You can cancel and resume the update process. As long as the device is powered on, it will continue
where it left.
